### ISSUE TITLE
program says its in stock but the website does not

### ISSUE THREAD

**Issue by DotsonEli** [miketalley/xbox-series-x-finder#2]
i found that some times the program says that its in stock when it is out of stock on there website

**Comment by miketalley** [comment]
Yeah, the underlying data is based on popfindr data. I don't know how they get the updated inventory, but I have also seen this. I would assume that the app is correct and the website is not, surprisingly.

Did you try calling the store? I got my Xbox from Target when the app said they had 10 but the website said "out of stock". Turns out they did have some inventory, can't confirm it was 10, but I can confirm it was at least 3.
